<a href="https://colab.research.google.com/github/Neha-Chandrika/EL_ClassRoom/blob/main/psNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%pip install numpy
import numpy as np
print(np.__version__)

2.0.2


In [ ]:
import numpy as np

a = np.array([1,2,3,4,5,6]) #1D array
print(a)

#2D array

b = np.array([[1,2,3],
             [5,6,7]])
print(b)



[1 2 3 4 5 6]
[[1 2 3]
 [5 6 7]]


In [ ]:
print(b.shape)

(2, 3)


In [ ]:
#Basic operations on array
c = np.array([10,20,30,60])
print(a)
print(a + 4)
print(a * 10)
print(a / 2)
print(a ** 2)
print(a % 2)

[1 2 3 4]
[5 6 7 8]
[10 20 30 40]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[1 0 1 0]


In [ ]:
#Elementary-wise operations with two arrays

x = np.array([1,2,3])
y = np.array([10,20,30])

print("the x array " , x)
print("the y array " , y)
print(x + y)
print(x - y)
print(x / y)
print(x % y)
print(x ** y)
print(x * y)

the x array  [1 2 3]
the y array  [10 20 30]
[11 22 33]
[ -9 -18 -27]
[0.1 0.1 0.1]
[1 2 3]
[              1         1048576 205891132094649]
[10 40 90]


In [ ]:
#very imp 2 questions

data = np.array([10, 20, 30, 40, 50])

print(data.mean()) #average
print(data.sum()) #total sum
print(data.min()) #minimum
print(data.max()) #maximum
print(data.std()) #standard deviation
#till here mam
print(data.var())
print(data.cumsum())
print(data.cumprod())

30.0
150
10
50
14.142135623730951
200.0
[ 10  30  60 100 150]
[      10      200     6000   240000 12000000]


In [ ]:
#2D array (matrices)  and indexing, Creating, accessing elements
m = np.array([[1,2,3],
             [4,5,6]])

print(m[0,0]) #fisrt row, first column -> 1
print(m[1,2]) #second row, third column


#first row
print(m[0,:])

#first column
print(m[:,0])

1
6
[1 2 3]
[1 4]


In [ ]:
a = np.array([1,2,3,4,5,6])
print(b.reshape(2,3))

[[1 2 3]
 [5 6 7]]


In [ ]:
#mathematical functions

a = np.array([[1,2],
             [3,4]])
b = np.array([[5,6],
              [7,8]])

print("Add: ", np.add(a,b))
print("Subtract:", np.subtract(a,b))
print("Multiply:", np.multiply(a,b))
print("Divide: ",np.divide(a,b))
print("Square Root:", np.sqrt(a))
print("Power:", np.power(a,3))


Add:  [[ 6  8]
 [10 12]]
Subtract: [[-4 -4]
 [-4 -4]]
Multiply: [[ 5 12]
 [21 32]]
Divide:  [[0.2        0.33333333]
 [0.42857143 0.5       ]]
Square Root: [[1.         1.41421356]
 [1.73205081 2.        ]]
Power: [[ 1  8]
 [27 64]]


In [ ]:
#linear
x = np.array([1,2,3])
y = np.array([10,20,30])

print(np.dot(x,y)) #dot product between two vector

140


In [ ]:
m = np.array([[1,2],
             [4,5]])

print(np.linalg.inv(m)) #inverse of a matrix
#NOTE : Last 2 dimensions of the array must be square


[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


In [ ]:
#creating special arrays , NumPy can create without starting from lists

zeroes = np.zeros((2,3)) # 2x3 array of 0s
print(zeroes)
ones = np.ones((3,3))
print(ones)
range_arr = np.arange(0,10,2)
print(range_arr)
linspace_arr = np.linspace(0,1,5)
print(linspace_arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
A = np.array([[1,2],
              [3,4]])
B = np.array([[5,6],
              [7,8]])

c = A @ B
print(c)

print(A.T)

print(np.eye)

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
<function eye at 0x7c784f5e2160>


In [ ]:
print(np.random.rand())
print(np.random.rand(5))
print(np.random.randint(1,9))

a = np.random.randint(1,100,size = 5)
print(a)

fruits = np.array(["apple","banana","cherry","mango"])
print(np.random.choice(fruits)) #one random item
print(np.random.choice(fruits,2)) #two random items

0.8454630269821303
[0.52641965 0.89186322 0.01550018 0.83153141 0.59806121]
8
[43 12 85 12 93]
cherry
['mango' 'cherry']
